export const metadata = {
  title: 'EGO - Test',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <div className='w-full mx-auto'>{children}</div>
  )
}
